name: Daily Climate Data Update

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch: 

permissions:
  contents: write 

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Pipeline
        run: |
          python src/data_pipeline/fetch_weather.py
          python src/analysis/feature_engineering.py
          python src/analysis/drought_index.py

      - name: Commit and Push Updated CSV
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Terralitik Auto-Bot"
          git add data/raw/ data/processed/
          
          if git diff --staged --quiet; then
            echo "Tidak ada data baru untuk di-commit."
          else
            git commit -m "Auto-update: Pembaruan data iklim harian & Prediksi AI"
            git push
          fi